services:
  redis:
    image: redis:8.4.0-alpine
    restart: on-failure
    container_name: redis_phone_book
    volumes:
      - ./.data/redis_data:/data
    ports:
     - "${REDIS_PORT}:${REDIS_PORT}"
    command: ["--port", "${REDIS_PORT}"]

  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_PORT: ${APP_PORT}
    image: phone_book_app
    container_name: phone_book_app
    ports:
      - "${APP_PORT}:${APP_PORT}"
    depends_on:
      - redis